config/routes.rb
IwantthisstuffCom::Application.routes.draw do
  resources :wishlists

  resources :wishes
  root :to => 'wishlists#home'

end

app/models/wish.rb
class Wish < ActiveRecord::Base
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishes }
    end
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
    @wish = Wish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/new
  # GET /wishes/new.json
  def new
    @wish = Wish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(params[:wish])

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render json: @wish, status: :created, location: @wish }
      else
        format.html { render action: "new" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishes/1
  # PUT /wishes/1.json
  def update
    @wish = Wish.find(params[:id])

    respond_to do |format|
      if @wish.update_attributes(params[:wish])
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  # GET /wishlists
  # GET /wishlists.json

  def home

  end

  def index
    @wishlists = Wishlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishlists }
    end
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
    @wishlist = Wishlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wishlist }
    end
  end

  # GET /wishlists/new
  # GET /wishlists/new.json
  def new
    @wishlist = Wishlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wishlist }
    end
  end

  # GET /wishlists/1/edit
  def edit
    @wishlist = Wishlist.find(params[:id])
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(params[:wishlist])

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render json: @wishlist, status: :created, location: @wishlist }
      else
        format.html { render action: "new" }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishlists/1
  # PUT /wishlists/1.json
  def update
    @wishlist = Wishlist.find(params[:id])

    respond_to do |format|
      if @wishlist.update_attributes(params[:wishlist])
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy

    respond_to do |format|
      format.html { redirect_to wishlists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iwantthisstuff</title>
  <%= stylesheet_link_tag    "/stylesheets/application.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishes.each do |wish| %>
  <tr>
    <td><%= link_to 'Show', wish %></td>
    <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
    <td><%= link_to 'Destroy', wish, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wish', new_wish_path %>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/home.html.erb
<div class='top_container'>
  <div class='banner'> 
    <div class='banner_text'>   
      <h1>I Want this stuff</h1>
      the best, (only?) website for sharing your wishlists with your facebook friends
    </div>
  </div>
</div> 
<div class='hero_image'>
  <%= image_tag('/images/grinch_santa.gif', :alt => 'grinch') %>
</div>
<div class='bubble_wrapper rounded'>
  <div class='hero_bubble rounded'>
    <div class='hero_inner rounded'>
      <h1>The Grinch stole your wishlist</h1>
    </div>
  </div>
</div>

app/views/wishlists/index.html.erb
<h1>Listing wishlists</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishlists.each do |wishlist| %>
  <tr>
    <td><%= link_to 'Show', wishlist %></td>
    <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
    <td><%= link_to 'Destroy', wishlist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>